SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'customer';

select * from customer;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , round(avg(purchase_amount), 2) as "amount"
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type
order by  avg(purchase_amount) desc;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
 	   COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
from customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
	round(100* sum(case when  discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as "discount rate"
	from customer
	group by item_purchased
	order by "discount rate" desc
	limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cus_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer 
)
select customer_segment as "Customer Segment", count(*) AS "Number of Customers" 
from cus_type
group by customer_segment;




--Q8. What are the top 3 most purchased products within each category? 

With itemcounts as (
select category, item_purchased, count(customer_id) as "total_orders" ,
Row_number() over(partition by category order by count(customer_id) desc ) as "item_rank"
from customer
group by category, item_purchased
)
select item_rank as "Rank", category as "Category", item_purchased as "Item Purchased", total_orders as "Total Orders"
from itemcounts
where item_rank<= 3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
with may_subscribe as (
select customer_id, previous_purchases, subscription_status,
	round (100 * sum(case
						when subscription_status = 'Yes' then 1 else 0 end)/count(*), 2) as percentage
	from customer
	group by customer_id, previous_purchases, subscription_status
	having previous_purchases> 5
						)
 select customer_id, previous_purchases, (case when percentage >50 then 'Yes' else 'NO' end) as probable_subscription
 from may_subscribe
 order by previous_purchases;



SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount)
from customer
group by age_group 
order by sum(purchase_amount) desc;
